export const spinReactions = [
	'Ah. This old chestnut.',
	'Bold choice by the wheel. Regrettable, but bold.',
	"Everyone's favourite. Not ours, but everyone's.",
	'Buckle up.',
	'We already know how this ends: badly.',
	'The people love this one. We remain deeply skeptical.',
	'Here we go again.',
	'Fate has spoken. Fate has terrible taste.',
	"Statistically, someone's crying happy tears about this. Not us.",
	"Let's see if this makes it past twenty minutes.",
	'Another crowd-pleaser. We are not the crowd.',
	"This one's got a cult following. About to see why we're not in it.",
	'Prepare to be underwhelmed, allegedly.',
	'The wheel has cursed us once more.',
	"Apparently a classic. We'll be the judge of that.",
	'Great. Just great.',
	'A beloved favourite, by all accounts except possibly ours.',
	'Sit down. This might take a while.',
	'The algorithm of fate strikes again.',
	'We have been chosen. We did not choose this.',
	'Ah yes, the one everyone quotes and nobody actually finishes.',
	'Cinema, apparently.',
	'The internet assures us this one is a masterpiece.',
	'Someone, somewhere, is defending this film right now.',
	"We're contractually obligated to watch this now.",
	'This has main-character syndrome written all over it.',
	'A modern classic, or so we keep being told.',
	'The wheel giveth. The wheel also ruins evenings.',
	"Popcorn's ready. Expectations are not.",
	"This one's got merchandise. That's never a good sign.",
	'We can already hear the sequel being pitched.',
	'Somewhere, a film critic is weeping with joy about this one.',
	'This will either be brilliant or a war crime. No in between.',
	'The reviews say "iconic." We say "we\'ll see."',
	'Grab a blanket. This could go either way.',
	'A beloved classic that time has apparently been kind to. We shall check.',
	'This one has won awards. Suspicious.',
	'Deep breath. Here we go.',
	'Everyone says this has quotable lines. We remain unconvinced.',
	'We hear this one changed people\'s lives. Bold claim.',
	'This is apparently "peak cinema." Cinema, please do better.',
	'The wheel spins, the regret begins.',
	'We did not choose this. The wheel chose this. Blame the wheel.',
	'Hope you weren\'t attached to your evening plans.',
	'A five-star darling, allegedly.',
	'Word on the street is this one is "unmissable." We shall see about that.',
	'Historians will one day ask why we did this to ourselves.',
	'This came very highly recommended. By whom, we cannot say.',
	'Well. Someone had to pick it.',
	'The wheel has a sense of humour. A cruel one.',
	'We were warned about this one. We ignored the warning.',
	'Rotten Tomatoes loves it. We are not a tomato.',
	'This one has a fanbase. An alarmingly devoted one.',
	'Somewhere a marketing department is very proud of this poster.',
	'We hear the merchandise outsold the movie. Concerning.',
	'A four-quadrant crowd-pleaser. We are, apparently, the fifth quadrant.',
	"This one's beloved. We'll try to see why.",
	'The trailer looked promising. Trailers lie.',
	'Ten out of ten, according to strangers on the internet.',
	'We have been advised to keep an open mind. Advice noted. Ignored.',
	'This one has a director\'s cut. We fear the theatrical cut already.',
	'A generation grew up on this. We did not.',
	'This has "instant classic" written all over the poster. Bold claim.',
	"Someone's favourite movie of all time. Someone who is not us.",
	'The wheel spun. The regret is imminent.',
	'This one comes with a content warning: mild disappointment likely.',
	'We hear this one is "a journey." We fear the destination.',
	'The people have spoken. The people are, once again, wrong.',
	'This film has a 90% score. We suspect the other 10% agree with us.',
	'Buckle in. Manage expectations. Regret accordingly.',
	'This one apparently "redefined the genre." We shall be the judge.',
	"Somewhere, someone's proposing marriage using a quote from this film.",
	'This has sequels. Plural. We should have seen this coming.',
	'The wheel giveth chaos, and chaos giveth this.',
	'A tale as old as time, or at least as old as the DVD shelf.',
	'This one has a Wikipedia page longer than some wars. Suspicious.',
	'Prepare the popcorn. Lower the expectations.',
	'We are told this one "holds up." We shall be the judges of that.',
	'The critics wept. We remain dry-eyed, for now.',
	'This one has won several awards it probably deserved. Allegedly.',
	'A generational touchstone, apparently. We touched nothing yet.',
	'This film has its own theme park ride. That tracks.',
	'We are legally obligated to have an opinion on this one now.',
	"Everyone quotes this. Let's see if it's earned.",
	'This one is "important cinema," according to somebody very serious.',
	'The algorithm suggested this. The algorithm knows nothing of us.',
	'We hear this one has a twist. We remain unmoved, for now.',
	"This is someone's comfort movie. It will not be ours.",
	'A five-star Sunday afternoon film, they say. It is not Sunday.',
	'This one made people cry in cinemas. We brought no tissues.',
	'The reviews use the word "masterpiece" a suspicious number of times.',
	'This one has a director\'s commentary. We do not need it. Yet.',
	'A staple of every "best films ever" list. We remain sceptical of lists.',
	'This film changed cinema forever, apparently. Forever is a long time.',
	'We hear the soundtrack alone is worth the ticket price. Adjusting expectations.',
	'This one is "for the whole family." Regret, it turns out, is too.',
	'Word has it this one is unmissable. We shall attempt to miss it emotionally.'
];

export function randomReaction() {
	return spinReactions[Math.floor(Math.random() * spinReactions.length)];
}
