export const spinReactions = [
	'Ah. This old chestnut.',
	'Bold choice by the wheel. Regrettable, but bold.',
	"Everyone's favourite. Not ours, but everyone's.",
	'Buckle up.',
	'We already know how this ends: badly.',
	'The people love this one. We remain deeply skeptical.',
	'Here we go again.',
	'Fate has spoken. Fate has terrible taste.',
	"Statistically, someone's crying happy tears about this. Not us.",
	"Let's see if this makes it past twenty minutes.",
	'Another crowd-pleaser. We are not the crowd.',
	"This one's got a cult following. About to see why we're not in it.",
	'Prepare to be underwhelmed, allegedly.',
	'The wheel has cursed us once more.',
	"Apparently a classic. We'll be the judge of that.",
	'Great. Just great.',
	'A beloved favourite, by all accounts except possibly ours.',
	'Sit down. This might take a while.',
	'The algorithm of fate strikes again.',
	'We have been chosen. We did not choose this.',
	'Ah yes, the one everyone quotes and nobody actually finishes.',
	'Cinema, apparently.',
	'The internet assures us this one is a masterpiece.',
	'Someone, somewhere, is defending this film right now.',
	"We're contractually obligated to watch this now.",
	'This has main-character syndrome written all over it.',
	'A modern classic, or so we keep being told.',
	'The wheel giveth. The wheel also ruins evenings.',
	"Popcorn's ready. Expectations are not.",
	"This one's got merchandise. That's never a good sign.",
	'We can already hear the sequel being pitched.',
	'Somewhere, a film critic is weeping with joy about this one.',
	'This will either be brilliant or a war crime. No in between.',
	'The reviews say "iconic." We say "we\'ll see."',
	'Grab a blanket. This could go either way.',
	'A beloved classic that time has apparently been kind to. We shall check.',
	'This one has won awards. Suspicious.',
	'Deep breath. Here we go.',
	'Everyone says this has quotable lines. We remain unconvinced.',
	'We hear this one changed people\'s lives. Bold claim.',
	'This is apparently "peak cinema." Cinema, please do better.',
	'The wheel spins, the regret begins.',
	'We did not choose this. The wheel chose this. Blame the wheel.',
	'Hope you weren\'t attached to your evening plans.',
	'A five-star darling, allegedly.',
	'Word on the street is this one is "unmissable." We shall see about that.',
	'Historians will one day ask why we did this to ourselves.',
	'This came very highly recommended. By whom, we cannot say.',
	'Well. Someone had to pick it.'
];

export function randomReaction() {
	return spinReactions[Math.floor(Math.random() * spinReactions.length)];
}
