import type { MediaType } from './tmdb';

export type SeedEntry = { title: string; mediaType: MediaType; year?: string };

export const seedList: SeedEntry[] = [
	// Harry Potter
	{ title: 'Harry Potter and the Philosopher\'s Stone', mediaType: 'movie', year: '2001' },
	{ title: 'Harry Potter and the Chamber of Secrets', mediaType: 'movie', year: '2002' },
	{ title: 'Harry Potter and the Prisoner of Azkaban', mediaType: 'movie', year: '2004' },
	{ title: 'Harry Potter and the Goblet of Fire', mediaType: 'movie', year: '2005' },
	{ title: 'Harry Potter and the Order of the Phoenix', mediaType: 'movie', year: '2007' },
	{ title: 'Harry Potter and the Half-Blood Prince', mediaType: 'movie', year: '2009' },
	{ title: 'Harry Potter and the Deathly Hallows: Part 1', mediaType: 'movie', year: '2010' },
	{ title: 'Harry Potter and the Deathly Hallows: Part 2', mediaType: 'movie', year: '2011' },

	// Twilight
	{ title: 'Twilight', mediaType: 'movie', year: '2008' },
	{ title: 'The Twilight Saga: New Moon', mediaType: 'movie', year: '2009' },
	{ title: 'The Twilight Saga: Eclipse', mediaType: 'movie', year: '2010' },
	{ title: 'The Twilight Saga: Breaking Dawn - Part 1', mediaType: 'movie', year: '2011' },
	{ title: 'The Twilight Saga: Breaking Dawn - Part 2', mediaType: 'movie', year: '2012' },

	// X-Men / Wolverine
	{ title: 'X-Men', mediaType: 'movie', year: '2000' },
	{ title: 'X2', mediaType: 'movie', year: '2003' },
	{ title: 'X-Men: The Last Stand', mediaType: 'movie', year: '2006' },
	{ title: 'X-Men Origins: Wolverine', mediaType: 'movie', year: '2009' },
	{ title: 'X-Men: First Class', mediaType: 'movie', year: '2011' },
	{ title: 'The Wolverine', mediaType: 'movie', year: '2013' },
	{ title: 'X-Men: Days of Future Past', mediaType: 'movie', year: '2014' },
	{ title: 'X-Men: Apocalypse', mediaType: 'movie', year: '2016' },
	{ title: 'Logan', mediaType: 'movie', year: '2017' },
	{ title: 'Dark Phoenix', mediaType: 'movie', year: '2019' },

	// Star Wars
	{ title: 'Star Wars', mediaType: 'movie', year: '1977' },
	{ title: 'The Empire Strikes Back', mediaType: 'movie', year: '1980' },
	{ title: 'Return of the Jedi', mediaType: 'movie', year: '1983' },
	{ title: 'Star Wars: Episode I - The Phantom Menace', mediaType: 'movie', year: '1999' },
	{ title: 'Star Wars: Episode II - Attack of the Clones', mediaType: 'movie', year: '2002' },
	{ title: 'Star Wars: Episode III - Revenge of the Sith', mediaType: 'movie', year: '2005' },
	{ title: 'Star Wars: The Force Awakens', mediaType: 'movie', year: '2015' },
	{ title: 'Star Wars: The Last Jedi', mediaType: 'movie', year: '2017' },
	{ title: 'Star Wars: The Rise of Skywalker', mediaType: 'movie', year: '2019' },

	// Lord of the Rings / Hobbit
	{ title: 'The Lord of the Rings: The Fellowship of the Ring', mediaType: 'movie', year: '2001' },
	{ title: 'The Lord of the Rings: The Two Towers', mediaType: 'movie', year: '2002' },
	{ title: 'The Lord of the Rings: The Return of the King', mediaType: 'movie', year: '2003' },
	{ title: 'The Hobbit: An Unexpected Journey', mediaType: 'movie', year: '2012' },
	{ title: 'The Hobbit: The Desolation of Smaug', mediaType: 'movie', year: '2013' },
	{ title: 'The Hobbit: The Battle of the Five Armies', mediaType: 'movie', year: '2014' },

	// Spider-Man
	{ title: 'Spider-Man', mediaType: 'movie', year: '2002' },
	{ title: 'Spider-Man 2', mediaType: 'movie', year: '2004' },
	{ title: 'Spider-Man 3', mediaType: 'movie', year: '2007' },
	{ title: 'The Amazing Spider-Man', mediaType: 'movie', year: '2012' },
	{ title: 'The Amazing Spider-Man 2', mediaType: 'movie', year: '2014' },
	{ title: 'Spider-Man: Homecoming', mediaType: 'movie', year: '2017' },
	{ title: 'Spider-Man: Far From Home', mediaType: 'movie', year: '2019' },
	{ title: 'Spider-Man: No Way Home', mediaType: 'movie', year: '2021' },

	// Batman
	{ title: 'Batman Begins', mediaType: 'movie', year: '2005' },
	{ title: 'The Dark Knight', mediaType: 'movie', year: '2008' },
	{ title: 'The Dark Knight Rises', mediaType: 'movie', year: '2012' },
	{ title: 'Batman v Superman: Dawn of Justice', mediaType: 'movie', year: '2016' },
	{ title: 'The Batman', mediaType: 'movie', year: '2022' },

	// Marvel / Avengers
	{ title: 'Iron Man', mediaType: 'movie', year: '2008' },
	{ title: 'Captain America: The First Avenger', mediaType: 'movie', year: '2011' },
	{ title: 'Thor', mediaType: 'movie', year: '2011' },
	{ title: 'The Avengers', mediaType: 'movie', year: '2012' },
	{ title: 'Guardians of the Galaxy', mediaType: 'movie', year: '2014' },
	{ title: 'Avengers: Age of Ultron', mediaType: 'movie', year: '2015' },
	{ title: 'Black Panther', mediaType: 'movie', year: '2018' },
	{ title: 'Avengers: Infinity War', mediaType: 'movie', year: '2018' },
	{ title: 'Captain Marvel', mediaType: 'movie', year: '2019' },
	{ title: 'Avengers: Endgame', mediaType: 'movie', year: '2019' },
	{ title: 'Doctor Strange', mediaType: 'movie', year: '2016' },

	// Indiana Jones
	{ title: 'Raiders of the Lost Ark', mediaType: 'movie', year: '1981' },
	{ title: 'Indiana Jones and the Temple of Doom', mediaType: 'movie', year: '1984' },
	{ title: 'Indiana Jones and the Last Crusade', mediaType: 'movie', year: '1989' },
	{ title: 'Indiana Jones and the Kingdom of the Crystal Skull', mediaType: 'movie', year: '2008' },

	// TV shows everyone loves that you're pretty sure you won't
	{ title: 'Friends', mediaType: 'tv' },
	{ title: 'The Big Bang Theory', mediaType: 'tv' },
	{ title: 'Game of Thrones', mediaType: 'tv', year: '2011' },
	{ title: 'Breaking Bad', mediaType: 'tv', year: '2008' },
	{ title: 'The Office', mediaType: 'tv', year: '2005' },
	{ title: 'Stranger Things', mediaType: 'tv', year: '2016' },
	{ title: 'The Walking Dead', mediaType: 'tv', year: '2010' },
	{ title: "Grey's Anatomy", mediaType: 'tv', year: '2005' },
	{ title: 'How I Met Your Mother', mediaType: 'tv', year: '2005' },
	{ title: 'Seinfeld', mediaType: 'tv', year: '1989' },
	{ title: 'The Simpsons', mediaType: 'tv', year: '1989' },
	{ title: 'Doctor Who', mediaType: 'tv', year: '2005' },
	{ title: 'Sherlock', mediaType: 'tv', year: '2010' },
	{ title: 'Downton Abbey', mediaType: 'tv', year: '2010' },
	{ title: 'Lost', mediaType: 'tv', year: '2004' },
	{ title: 'Prison Break', mediaType: 'tv', year: '2005' },
	{ title: 'Suits', mediaType: 'tv', year: '2011' },
	{ title: 'The Crown', mediaType: 'tv', year: '2016' },
	{ title: 'Peaky Blinders', mediaType: 'tv', year: '2013' },
	{ title: 'Money Heist', mediaType: 'tv', year: '2017' },
	{ title: 'Squid Game', mediaType: 'tv', year: '2021' },
	{ title: 'Wednesday', mediaType: 'tv', year: '2022' },
	{ title: 'The Mandalorian', mediaType: 'tv', year: '2019' },
	{ title: 'WandaVision', mediaType: 'tv', year: '2021' },
	{ title: 'Loki', mediaType: 'tv', year: '2021' },

	// More Marvel
	{ title: 'Iron Man 2', mediaType: 'movie', year: '2010' },
	{ title: 'Iron Man 3', mediaType: 'movie', year: '2013' },
	{ title: 'Thor: The Dark World', mediaType: 'movie', year: '2013' },
	{ title: 'Thor: Ragnarok', mediaType: 'movie', year: '2017' },
	{ title: 'Thor: Love and Thunder', mediaType: 'movie', year: '2022' },
	{ title: 'Captain America: The Winter Soldier', mediaType: 'movie', year: '2014' },
	{ title: 'Captain America: Civil War', mediaType: 'movie', year: '2016' },
	{ title: 'Ant-Man', mediaType: 'movie', year: '2015' },
	{ title: 'Ant-Man and the Wasp', mediaType: 'movie', year: '2018' },
	{ title: 'Ant-Man and the Wasp: Quantumania', mediaType: 'movie', year: '2023' },
	{ title: 'Guardians of the Galaxy Vol. 2', mediaType: 'movie', year: '2017' },
	{ title: 'Guardians of the Galaxy Vol. 3', mediaType: 'movie', year: '2023' },
	{ title: 'Black Widow', mediaType: 'movie', year: '2021' },
	{ title: 'Shang-Chi and the Legend of the Ten Rings', mediaType: 'movie', year: '2021' },
	{ title: 'Eternals', mediaType: 'movie', year: '2021' },
	{ title: 'Doctor Strange in the Multiverse of Madness', mediaType: 'movie', year: '2022' },
	{ title: 'Black Panther: Wakanda Forever', mediaType: 'movie', year: '2022' },
	{ title: 'The Marvels', mediaType: 'movie', year: '2023' },
	{ title: 'Deadpool', mediaType: 'movie', year: '2016' },
	{ title: 'Deadpool 2', mediaType: 'movie', year: '2018' },
	{ title: 'Deadpool & Wolverine', mediaType: 'movie', year: '2024' },
	{ title: 'Venom', mediaType: 'movie', year: '2018' },
	{ title: 'Venom: Let There Be Carnage', mediaType: 'movie', year: '2021' },
	{ title: 'Morbius', mediaType: 'movie', year: '2022' },

	// DC
	{ title: 'Man of Steel', mediaType: 'movie', year: '2013' },
	{ title: 'Wonder Woman', mediaType: 'movie', year: '2017' },
	{ title: 'Justice League', mediaType: 'movie', year: '2017' },
	{ title: 'Aquaman', mediaType: 'movie', year: '2018' },
	{ title: 'Shazam!', mediaType: 'movie', year: '2019' },
	{ title: 'Joker', mediaType: 'movie', year: '2019' },
	{ title: 'Wonder Woman 1984', mediaType: 'movie', year: '2020' },
	{ title: "Zack Snyder's Justice League", mediaType: 'movie', year: '2021' },
	{ title: 'The Suicide Squad', mediaType: 'movie', year: '2021' },
	{ title: 'Black Adam', mediaType: 'movie', year: '2022' },
	{ title: 'Aquaman and the Lost Kingdom', mediaType: 'movie', year: '2023' },

	// Fast & Furious
	{ title: 'The Fast and the Furious', mediaType: 'movie', year: '2001' },
	{ title: '2 Fast 2 Furious', mediaType: 'movie', year: '2003' },
	{ title: 'The Fast and the Furious: Tokyo Drift', mediaType: 'movie', year: '2006' },
	{ title: 'Fast & Furious', mediaType: 'movie', year: '2009' },
	{ title: 'Fast Five', mediaType: 'movie', year: '2011' },
	{ title: 'Fast & Furious 6', mediaType: 'movie', year: '2013' },
	{ title: 'Furious 7', mediaType: 'movie', year: '2015' },
	{ title: 'The Fate of the Furious', mediaType: 'movie', year: '2017' },
	{ title: 'F9', mediaType: 'movie', year: '2021' },
	{ title: 'Fast X', mediaType: 'movie', year: '2023' },

	// Transformers
	{ title: 'Transformers', mediaType: 'movie', year: '2007' },
	{ title: 'Transformers: Revenge of the Fallen', mediaType: 'movie', year: '2009' },
	{ title: 'Transformers: Dark of the Moon', mediaType: 'movie', year: '2011' },
	{ title: 'Transformers: Age of Extinction', mediaType: 'movie', year: '2014' },
	{ title: 'Transformers: The Last Knight', mediaType: 'movie', year: '2017' },
	{ title: 'Bumblebee', mediaType: 'movie', year: '2018' },

	// Jurassic Park / World
	{ title: 'Jurassic Park', mediaType: 'movie', year: '1993' },
	{ title: 'The Lost World: Jurassic Park', mediaType: 'movie', year: '1997' },
	{ title: 'Jurassic Park III', mediaType: 'movie', year: '2001' },
	{ title: 'Jurassic World', mediaType: 'movie', year: '2015' },
	{ title: 'Jurassic World: Fallen Kingdom', mediaType: 'movie', year: '2018' },
	{ title: 'Jurassic World Dominion', mediaType: 'movie', year: '2022' },

	// Mission: Impossible
	{ title: 'Mission: Impossible', mediaType: 'movie', year: '1996' },
	{ title: 'Mission: Impossible II', mediaType: 'movie', year: '2000' },
	{ title: 'Mission: Impossible III', mediaType: 'movie', year: '2006' },
	{ title: 'Mission: Impossible - Ghost Protocol', mediaType: 'movie', year: '2011' },
	{ title: 'Mission: Impossible - Rogue Nation', mediaType: 'movie', year: '2015' },
	{ title: 'Mission: Impossible - Fallout', mediaType: 'movie', year: '2018' },
	{ title: 'Mission: Impossible - Dead Reckoning Part One', mediaType: 'movie', year: '2023' },

	// Pirates of the Caribbean
	{ title: 'Pirates of the Caribbean: The Curse of the Black Pearl', mediaType: 'movie', year: '2003' },
	{ title: "Pirates of the Caribbean: Dead Man's Chest", mediaType: 'movie', year: '2006' },
	{ title: "Pirates of the Caribbean: At World's End", mediaType: 'movie', year: '2007' },
	{ title: 'Pirates of the Caribbean: On Stranger Tides', mediaType: 'movie', year: '2011' },
	{ title: 'Pirates of the Caribbean: Dead Men Tell No Tales', mediaType: 'movie', year: '2017' },

	// The Matrix
	{ title: 'The Matrix', mediaType: 'movie', year: '1999' },
	{ title: 'The Matrix Reloaded', mediaType: 'movie', year: '2003' },
	{ title: 'The Matrix Revolutions', mediaType: 'movie', year: '2003' },
	{ title: 'The Matrix Resurrections', mediaType: 'movie', year: '2021' },

	// Terminator
	{ title: 'The Terminator', mediaType: 'movie', year: '1984' },
	{ title: 'Terminator 2: Judgment Day', mediaType: 'movie', year: '1991' },
	{ title: 'Terminator 3: Rise of the Machines', mediaType: 'movie', year: '2003' },
	{ title: 'Terminator Salvation', mediaType: 'movie', year: '2009' },
	{ title: 'Terminator Genisys', mediaType: 'movie', year: '2015' },
	{ title: 'Terminator: Dark Fate', mediaType: 'movie', year: '2019' },

	// Alien / Predator
	{ title: 'Alien', mediaType: 'movie', year: '1979' },
	{ title: 'Aliens', mediaType: 'movie', year: '1986' },
	{ title: 'Predator', mediaType: 'movie', year: '1987' },

	// YA franchises
	{ title: 'The Hunger Games', mediaType: 'movie', year: '2012' },
	{ title: 'The Hunger Games: Catching Fire', mediaType: 'movie', year: '2013' },
	{ title: 'The Hunger Games: Mockingjay - Part 1', mediaType: 'movie', year: '2014' },
	{ title: 'The Hunger Games: Mockingjay - Part 2', mediaType: 'movie', year: '2015' },
	{ title: 'The Hunger Games: The Ballad of Songbirds & Snakes', mediaType: 'movie', year: '2023' },
	{ title: 'Divergent', mediaType: 'movie', year: '2014' },
	{ title: 'Insurgent', mediaType: 'movie', year: '2015' },
	{ title: 'Allegiant', mediaType: 'movie', year: '2016' },
	{ title: 'The Maze Runner', mediaType: 'movie', year: '2014' },
	{ title: 'Maze Runner: The Scorch Trials', mediaType: 'movie', year: '2015' },
	{ title: 'Maze Runner: The Death Cure', mediaType: 'movie', year: '2018' },
	{ title: 'Percy Jackson & the Olympians: The Lightning Thief', mediaType: 'movie', year: '2010' },
	{ title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', mediaType: 'movie', year: '2005' },
	{ title: 'The Chronicles of Narnia: Prince Caspian', mediaType: 'movie', year: '2008' },
	{ title: 'The Chronicles of Narnia: The Voyage of the Dawn Treader', mediaType: 'movie', year: '2010' },
	{ title: 'The Golden Compass', mediaType: 'movie', year: '2007' },

	// Beloved animated films
	{ title: 'How to Train Your Dragon', mediaType: 'movie', year: '2010' },
	{ title: 'How to Train Your Dragon 2', mediaType: 'movie', year: '2014' },
	{ title: 'How to Train Your Dragon: The Hidden World', mediaType: 'movie', year: '2019' },
	{ title: 'Frozen', mediaType: 'movie', year: '2013' },
	{ title: 'Frozen II', mediaType: 'movie', year: '2019' },
	{ title: 'Shrek', mediaType: 'movie', year: '2001' },
	{ title: 'Shrek 2', mediaType: 'movie', year: '2004' },
	{ title: 'Shrek the Third', mediaType: 'movie', year: '2007' },
	{ title: 'Shrek Forever After', mediaType: 'movie', year: '2010' },
	{ title: 'Despicable Me', mediaType: 'movie', year: '2010' },
	{ title: 'Despicable Me 2', mediaType: 'movie', year: '2013' },
	{ title: 'Minions', mediaType: 'movie', year: '2015' },
	{ title: 'Toy Story', mediaType: 'movie', year: '1995' },
	{ title: 'Toy Story 2', mediaType: 'movie', year: '1999' },
	{ title: 'Toy Story 3', mediaType: 'movie', year: '2010' },
	{ title: 'Toy Story 4', mediaType: 'movie', year: '2019' },
	{ title: 'Finding Nemo', mediaType: 'movie', year: '2003' },
	{ title: 'Finding Dory', mediaType: 'movie', year: '2016' },
	{ title: 'The Incredibles', mediaType: 'movie', year: '2004' },
	{ title: 'Incredibles 2', mediaType: 'movie', year: '2018' },
	{ title: 'Cars', mediaType: 'movie', year: '2006' },
	{ title: 'Ice Age', mediaType: 'movie', year: '2002' },
	{ title: 'Madagascar', mediaType: 'movie', year: '2005' },
	{ title: 'Kung Fu Panda', mediaType: 'movie', year: '2008' },
	{ title: 'Up', mediaType: 'movie', year: '2009' },
	{ title: 'Inside Out', mediaType: 'movie', year: '2015' },
	{ title: 'Coco', mediaType: 'movie', year: '2017' },
	{ title: 'Beauty and the Beast', mediaType: 'movie', year: '2017' },
	{ title: 'Aladdin', mediaType: 'movie', year: '2019' },
	{ title: 'The Lion King', mediaType: 'movie', year: '2019' },
	{ title: 'Moana', mediaType: 'movie', year: '2016' },
	{ title: 'Zootopia', mediaType: 'movie', year: '2016' },
	{ title: 'Wreck-It Ralph', mediaType: 'movie', year: '2012' },

	// James Bond
	{ title: 'Dr. No', mediaType: 'movie', year: '1962' },
	{ title: 'From Russia with Love', mediaType: 'movie', year: '1963' },
	{ title: 'Goldfinger', mediaType: 'movie', year: '1964' },
	{ title: 'Thunderball', mediaType: 'movie', year: '1965' },
	{ title: 'You Only Live Twice', mediaType: 'movie', year: '1967' },
	{ title: "On Her Majesty's Secret Service", mediaType: 'movie', year: '1969' },
	{ title: 'Diamonds Are Forever', mediaType: 'movie', year: '1971' },
	{ title: 'Live and Let Die', mediaType: 'movie', year: '1973' },
	{ title: 'The Man with the Golden Gun', mediaType: 'movie', year: '1974' },
	{ title: 'The Spy Who Loved Me', mediaType: 'movie', year: '1977' },
	{ title: 'Moonraker', mediaType: 'movie', year: '1979' },
	{ title: 'For Your Eyes Only', mediaType: 'movie', year: '1981' },
	{ title: 'Octopussy', mediaType: 'movie', year: '1983' },
	{ title: 'A View to a Kill', mediaType: 'movie', year: '1985' },
	{ title: 'The Living Daylights', mediaType: 'movie', year: '1987' },
	{ title: 'Licence to Kill', mediaType: 'movie', year: '1989' },
	{ title: 'GoldenEye', mediaType: 'movie', year: '1995' },
	{ title: 'Tomorrow Never Dies', mediaType: 'movie', year: '1997' },
	{ title: 'The World Is Not Enough', mediaType: 'movie', year: '1999' },
	{ title: 'Die Another Day', mediaType: 'movie', year: '2002' },
	{ title: 'Casino Royale', mediaType: 'movie', year: '2006' },
	{ title: 'Quantum of Solace', mediaType: 'movie', year: '2008' },
	{ title: 'Skyfall', mediaType: 'movie', year: '2012' },
	{ title: 'Spectre', mediaType: 'movie', year: '2015' },
	{ title: 'No Time to Die', mediaType: 'movie', year: '2021' },

	// More spy / action franchises in the same vein
	{ title: 'The Bourne Identity', mediaType: 'movie', year: '2002' },
	{ title: 'The Bourne Supremacy', mediaType: 'movie', year: '2004' },
	{ title: 'The Bourne Ultimatum', mediaType: 'movie', year: '2007' },
	{ title: 'The Bourne Legacy', mediaType: 'movie', year: '2012' },
	{ title: 'Jason Bourne', mediaType: 'movie', year: '2016' },
	{ title: 'Kingsman: The Secret Service', mediaType: 'movie', year: '2015' },
	{ title: 'Kingsman: The Golden Circle', mediaType: 'movie', year: '2017' },
	{ title: 'John Wick', mediaType: 'movie', year: '2014' },
	{ title: 'John Wick: Chapter 2', mediaType: 'movie', year: '2017' },
	{ title: 'John Wick: Chapter 3 - Parabellum', mediaType: 'movie', year: '2019' },
	{ title: 'John Wick: Chapter 4', mediaType: 'movie', year: '2023' },
	{ title: 'Die Hard', mediaType: 'movie', year: '1988' },
	{ title: 'Die Hard 2', mediaType: 'movie', year: '1990' },
	{ title: 'Die Hard with a Vengeance', mediaType: 'movie', year: '1995' },
	{ title: 'Live Free or Die Hard', mediaType: 'movie', year: '2007' },
	{ title: 'A Good Day to Die Hard', mediaType: 'movie', year: '2013' },
	{ title: "Ocean's Eleven", mediaType: 'movie', year: '2001' },
	{ title: "Ocean's Twelve", mediaType: 'movie', year: '2004' },
	{ title: "Ocean's Thirteen", mediaType: 'movie', year: '2007' },

	// Nolan / prestige sci-fi
	{ title: 'Inception', mediaType: 'movie', year: '2010' },
	{ title: 'Interstellar', mediaType: 'movie', year: '2014' },
	{ title: 'Dunkirk', mediaType: 'movie', year: '2017' },
	{ title: 'Tenet', mediaType: 'movie', year: '2020' },
	{ title: 'Oppenheimer', mediaType: 'movie', year: '2023' },

	// Beloved classics / prestige favourites
	{ title: 'Titanic', mediaType: 'movie', year: '1997' },
	{ title: 'Avatar', mediaType: 'movie', year: '2009' },
	{ title: 'Avatar: The Way of Water', mediaType: 'movie', year: '2022' },
	{ title: 'Gladiator', mediaType: 'movie', year: '2000' },
	{ title: 'Braveheart', mediaType: 'movie', year: '1995' },
	{ title: 'Forrest Gump', mediaType: 'movie', year: '1994' },
	{ title: 'The Shawshank Redemption', mediaType: 'movie', year: '1994' },
	{ title: 'The Godfather', mediaType: 'movie', year: '1972' },
	{ title: 'The Godfather Part II', mediaType: 'movie', year: '1974' },
	{ title: 'Pulp Fiction', mediaType: 'movie', year: '1994' },
	{ title: 'Fight Club', mediaType: 'movie', year: '1999' },
	{ title: 'Goodfellas', mediaType: 'movie', year: '1990' },
	{ title: 'Se7en', mediaType: 'movie', year: '1995' },

	// Horror / thriller crowd-pleasers
	{ title: 'Get Out', mediaType: 'movie', year: '2017' },
	{ title: 'A Quiet Place', mediaType: 'movie', year: '2018' },
	{ title: 'A Quiet Place Part II', mediaType: 'movie', year: '2021' },
	{ title: 'It', mediaType: 'movie', year: '2017' },
	{ title: 'It Chapter Two', mediaType: 'movie', year: '2019' },
	{ title: 'The Conjuring', mediaType: 'movie', year: '2013' },
	{ title: 'The Conjuring 2', mediaType: 'movie', year: '2016' },
	{ title: 'Us', mediaType: 'movie', year: '2019' },
	{ title: 'Hereditary', mediaType: 'movie', year: '2018' },

	// Musicals / biopics
	{ title: 'La La Land', mediaType: 'movie', year: '2016' },
	{ title: 'A Star Is Born', mediaType: 'movie', year: '2018' },
	{ title: 'Bohemian Rhapsody', mediaType: 'movie', year: '2018' },
	{ title: 'Elvis', mediaType: 'movie', year: '2022' },
	{ title: 'The Greatest Showman', mediaType: 'movie', year: '2017' },

	// Monster / creature blockbusters
	{ title: 'Godzilla', mediaType: 'movie', year: '2014' },
	{ title: 'Kong: Skull Island', mediaType: 'movie', year: '2017' },
	{ title: 'Godzilla vs. Kong', mediaType: 'movie', year: '2021' },
	{ title: 'Independence Day', mediaType: 'movie', year: '1996' },
	{ title: 'The Meg', mediaType: 'movie', year: '2018' },
	{ title: 'Twister', mediaType: 'movie', year: '1996' },

	// Comedy
	{ title: 'The Hangover', mediaType: 'movie', year: '2009' },
	{ title: 'The Hangover Part II', mediaType: 'movie', year: '2011' },
	{ title: 'Men in Black', mediaType: 'movie', year: '1997' },
	{ title: 'Men in Black II', mediaType: 'movie', year: '2002' },

	// More action / adventure
	{ title: 'Rocky', mediaType: 'movie', year: '1976' },
	{ title: 'Creed', mediaType: 'movie', year: '2015' },
	{ title: 'Creed II', mediaType: 'movie', year: '2018' },
	{ title: 'Star Trek', mediaType: 'movie', year: '2009' },
	{ title: 'Star Trek Into Darkness', mediaType: 'movie', year: '2013' },
	{ title: 'Rise of the Planet of the Apes', mediaType: 'movie', year: '2011' },
	{ title: 'Dawn of the Planet of the Apes', mediaType: 'movie', year: '2014' },
	{ title: 'War for the Planet of the Apes', mediaType: 'movie', year: '2017' },
	{ title: 'National Treasure', mediaType: 'movie', year: '2004' },
	{ title: 'Sherlock Holmes', mediaType: 'movie', year: '2009' },
	{ title: 'Sherlock Holmes: A Game of Shadows', mediaType: 'movie', year: '2011' }
];
